# Generated by Django 3.2.9 on 2021-12-27 09:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0004_auto_20211227_1445'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='contact',
            field=models.BigIntegerField(null=True),
        ),
    ]
