# Generated by Django 4.0 on 2022-03-09 16:53

from django.db import migrations
import phonenumber_field.modelfields


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0009_alter_orderitem_quantity'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='contact',
            field=phonenumber_field.modelfields.PhoneNumberField(max_length=128, null=True, region=None),
        ),
    ]
