# Generated by Django 4.0 on 2022-03-09 18:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0011_rename_city_shippingaddress_country_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='sphipping_address',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='store.shippingaddress'),
        ),
    ]
