# Generated by Django 4.0 on 2022-03-09 19:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0012_order_sphipping_address'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='shippingaddress',
            name='state',
        ),
    ]
